version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:123456@db:5432/foodapp
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    command: >
      sh -c "
            pip install --upgrade pip &&
            pip install -r requirements.txt &&
            if [ ! -d 'alembic' ]; then alembic init alembic; fi &&
            alembic upgrade head &&
            uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: foodapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  redis_data:
