"""add pool and pool_orders tables

Revision ID: a86626701f7e
Revises: b7fbaffb1221
Create Date: 2025-02-01 18:30:04.327299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86626701f7e'
down_revision: Union[str, None] = 'b7fbaffb1221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
